import React, { useState } from 'react';

export const appifyHelpTopics = [
  {id:'start',title:'Começar, salvar e proteger seus projetos',text:'Crie um projeto no painel inicial e personalize-o em Identidade. No Appify desktop, os projetos são salvos no computador. Use o botão Salvar e confira o estado de salvamento antes de fechar. Faça backups JSON regularmente. Backup preserva o projeto editável; o ZIP do PWA é para hospedagem. Duplicar cria uma cópia independente. Excluir remove o projeto selecionado.',steps:['Crie um projeto e defina nome, logotipo, ícone e idioma.','Adicione módulos e aulas em Módulos & Conteúdo.','Salve, reabra e faça um backup antes de alterações importantes.']},
  {id:'identity',title:'Identidade, idiomas e configurações',text:'Identidade controla nome, cores, logotipo, ícone e fontes. O idioma escolhido define a interface do PWA: português, inglês, espanhol ou francês. Você escreve o conteúdo das aulas no idioma desejado; o Appify não traduz automaticamente seus textos. Configurações reúne opções de exibição, offline, abertura e recursos por projeto. Alterações destinadas aos clientes exigem nova exportação e atualização da hospedagem.'},
  {id:'opening',title:'Abertura personalizada e instalação',text:'Em Configurações Técnicas, personalize o tempo e a animação do logotipo ou envie uma abertura em MP4, GIF, WebP, PNG ou JPG, de até 5 MB. Escolha mostrar a arte inteira ou preencher a tela. MP4 toca sem som, permite pular e tem limite de 10 segundos. Falha de vídeo usa a marca como alternativa. A abertura aparece após carregar o PWA; a primeira tela do sistema depende do celular. Boas-vindas oferece acesso ao conteúdo e instalação opcional. Para testar um primeiro acesso, use a prévia de abertura ou uma aba anônima.'},
  {id:'lessons',title:'Módulos e aulas',text:'Organize o produto em módulos e aulas. Módulos em rascunho não abrem para o cliente. Cada aula pode usar HTML ou uma fonte de conteúdo compatível com os campos disponíveis. Salvar Aula grava o conteúdo e as opções do Builder; confira também o salvamento do projeto. Configurações visuais de bloqueio ou oferta não substituem autenticação segura do comprador.'},
  {id:'builder',title:'Builder visual: textos, imagens, botões e containers',text:'O Builder permite montar o conteúdo em blocos, ajustar fontes, cores, espaçamento e alinhamento, duplicar elementos e reorganizar a aula. Use os containers de uma, duas ou três colunas conforme o conteúdo. A visualização de celular ajuda a conferir a disposição; valide também no aparelho real. Botão / Link oferece variações de aparência, tamanho e largura. Lista com ícones organiza itens; Card / Destaque enfatiza uma orientação; Acordeão abre e fecha seções, inclusive perguntas frequentes (FAQ).'},
  {id:'html',title:'HTML importado e atividades interativas',text:'HTML estático importado passa por tratamento de segurança e responsividade. Scripts arbitrários não são executados nesse modo. O modo interativo usa um ambiente isolado, com restrições de rede e recursos externos. Atividades que usam localStorage podem guardar histórico neste aparelho, separado por produto e aula. A prévia tem dados próprios, separados dos clientes. O botão Limpar histórico desta atividade apaga os registros locais; não há sincronização entre aparelhos. Limpar os dados do navegador também apaga o histórico. Nem toda página feita por outra ferramenta funcionará sem adaptação. Confira a prévia desktop e a versão exportada; mantenha os arquivos necessários na estrutura gerada pelo Appify.'},
  {id:'media',title:'Vídeo, áudio e materiais de apoio',text:'Vídeos do Builder podem usar YouTube com a apresentação configurada no Appify. A reprodução continua dependendo do serviço externo. Áudio aceita upload MP3 ou M4A de até 5 MB, incorporado ao projeto, ou link HTTPS direto para o arquivo. O player não inicia sozinho. Arquivo para download usa link HTTPS externo, título, descrição e texto do botão. O provedor pode mostrar o PDF antes de baixar. Teste fontes e links reais; uma página de compartilhamento nem sempre é um link direto de áudio.'},
  {id:'progress',title:'Progresso real e Continuar de onde parei',text:'O PWA salva as aulas marcadas como concluídas e a última aula acessada no próprio navegador, separadas por produto. Funciona com gamificação ligada ou desligada. O progresso de cada módulo considera apenas suas aulas atuais. Na tela inicial, Continuar de onde parei retoma a aula; se ela já foi concluída, sugere a próxima disponível. Se não houver outra, permite rever a última. Conteúdo removido, módulo em rascunho ou bloqueado não aparece como sugestão. A prévia tem seus próprios dados e não altera o progresso dos clientes. Não há sincronização entre dispositivos; limpar dados do navegador pode apagar as marcações.'},
  {id:'features',title:'Gamificação, engajamento e suporte',text:'Gamificação e engajamento podem ser habilitados por projeto. Desativar gamificação não desativa o salvamento de conclusão nem a retomada das aulas. Barras e anéis respeitam as escolhas visuais; celebrações dependem da configuração. Pontos, medalhas, sequências e recursos de comunidade/push ainda precisam de validação ou integração própria para representar uso real entre clientes; não trate prévias como resultados reais. Suporte permite configurar o canal de contato disponível no PWA.'},
  {id:'publication',title:'Exportar, publicar e atualizar',text:'Publicação organiza o fluxo em preparar o projeto, gerar o ZIP e seguir as instruções de hospedagem. Gerar ZIP não publica automaticamente. Extraia os arquivos e mantenha index.html na raiz da pasta enviada. Netlify e Cloudflare têm guias na aba. Para atualizar, envie a nova exportação ao mesmo projeto hospedado. Em Testar no celular — opcional, guarde o endereço HTTPS e use o QR para abrir o link. O QR não instala o aplicativo automaticamente. Domínio próprio é opcional e seu DNS é configurado na hospedagem.'},
  {id:'analytics',title:'Analytics mínimo e Supabase',text:'Analytics mostra aberturas de aulas, conclusões marcadas e cliques em ofertas ou materiais. Sem consulta real, o painel mostra — em vez de zeros fictícios. O backend Supabase precisa ser instalado e configurado antes de receber dados. A consulta exige sua conta de proprietário; não é o login do comprador. Ative a coleta por projeto e reexporte o PWA. Testes no Builder não contam; testes no PWA hospedado contam. Cliques não comprovam vendas, abertura não comprova consumo e conclusão não comprova aprendizado. A configuração técnica de implantação está documentada em docs/analytics-supabase.md no repositório.'},
  {id:'limits',title:'Offline, acesso e limites atuais',text:'O PWA pode guardar o aplicativo e conteúdo empacotado para uso offline conforme a configuração. Áudio incorporado acompanha o pacote; YouTube, links externos e serviços online dependem da internet. O modo offline não garante acesso a todos os recursos externos. A autenticação de compradores ainda não está implementada: conteúdo exportado com acesso aberto não é protegido apenas por pedir um e-mail. Nunca coloque senhas ou chaves administrativas em HTML, projeto público ou ZIP. A sessão de consulta dos relatórios fica apenas em memória.'},
];
export function AppifyDocumentation({onClose}:{onClose:()=>void}) {
  const [query,setQuery]=useState('');
  const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const filtered=appifyHelpTopics.filter(topic=>normalize(`${topic.title} ${topic.text} ${topic.steps?.join(' ') || ''}`).includes(normalize(query.trim())));
  return <article style={{maxWidth:960,paddingBottom:40}}>
    <div className="section-header"><div><h2 className="section-title">Ajuda e documentação</h2><p className="section-sub">Como usar o Appify e o que cada recurso faz nesta versão.</p></div><button className="btn-ghost" onClick={onClose}>Voltar ao projeto</button></div>
    <label className="vpb-label" htmlFor="documentation-search">Buscar uma funcionalidade</label><input id="documentation-search" className="vpb-input" type="search" placeholder="Ex.: áudio, publicar, progresso, Supabase…" value={query} onChange={event=>setQuery(event.target.value)} />
    <p style={{color:'var(--muted)',fontSize:13}}>Esta ajuda pertence ao editor Appify. Não aparece nas aulas dos seus clientes.</p>
    <nav aria-label="Tópicos da documentação" style={{display:'flex',flexWrap:'wrap',gap:8,margin:'20px 0'}}>{filtered.map(topic=><a key={topic.id} href={`#help-${topic.id}`} style={{color:'var(--accent)',fontSize:13,padding:'6px 10px',border:'1px solid var(--border)',borderRadius:8}}>{topic.title}</a>)}</nav>
    {filtered.length===0 && <p role="status">Nenhum tópico encontrado. Tente outra palavra.</p>}
    {filtered.map(topic=><section id={`help-${topic.id}`} key={topic.id} className="eng-card" style={{padding:20,marginBottom:16,scrollMarginTop:20}}><h3 style={{fontSize:18,marginBottom:12}}>{topic.title}</h3><p style={{lineHeight:1.7,fontSize:14,color:'var(--text)',margin:0}}>{topic.text}</p>{topic.steps && <ol style={{paddingLeft:20,lineHeight:1.7,fontSize:14}}>{topic.steps.map(step=><li key={step}>{step}</li>)}</ol>}</section>)}
  </article>;
}
