import assert from 'node:assert/strict';
import test from 'node:test';
import React,{act} from 'react';
import { JSDOM } from 'jsdom';
import type { PwaConfig } from '../types';
import { INITIAL_PWA_CONFIG } from '../constants';
import { TEST_SPLASH_MP4, TEST_SPLASH_GIF, TEST_SPLASH_WEBP } from '../utils/fixtures/splashMedia';
const dom=new JSDOM('<div id="root"></div>',{url:'https://appify.test/'});
Object.defineProperty(dom.window.navigator,'userAgent',{value:'Mozilla Android Chrome'});
Object.assign(globalThis,{window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,IS_REACT_ACT_ENVIRONMENT:true});
const { createRoot }=await import('react-dom/client');
await import('../i18n');
const { initializePwaInstall }=await import('../utils/pwaInstallation');
const { CustomerEntry,entryStorageKey,splashDuration }=await import('./CustomerEntry');
const controller=initializePwaInstall();
const config:PwaConfig={...INITIAL_PWA_CONFIG,appName:'Guia de Viagem',customSplash:false,language:'pt-BR' as const};
const button=(text:string)=>[...document.querySelectorAll('button')].find(b=>b.textContent?.includes(text))!;
const click=(node:HTMLElement)=>node.click();
async function render(settings=config) {
  const root=createRoot(document.getElementById('root')!);
  await act(async()=>root.render(React.createElement(CustomerEntry,{config:settings},React.createElement('div',{'data-testid':'library'},'Aulas'))));
  return root;
}
test('published product opens content directly without demo or email even with legacy demo settings, and returning users skip entry',async()=>{
  localStorage.clear();const root=await render({...config,customerAccessMode:'demo'});
  assert.match(document.body.textContent || '',/Guia de Viagem/);
  assert.equal(document.querySelector('[data-testid="library"]'),null);
  assert.equal(document.querySelector('input[type="email"]'),null);
  assert.doesNotMatch(document.body.textContent || '',/Demonstração|Experimente a tela/);
  await act(async()=>click(button('Acessar conteúdo')));
  assert.ok(document.querySelector('[data-testid="library"]'));
  assert.equal(localStorage.getItem(entryStorageKey(config.appName)),'done');
  assert.equal(JSON.stringify({...localStorage}).includes('test@example.com'),false);
  await act(async()=>root.unmount());
  const reopened=await render();assert.ok(document.querySelector('[data-testid="library"]'));await act(async()=>reopened.unmount());
});
test('login simulation is confined to preview and never stores the test email or marks real onboarding complete',async()=>{
  localStorage.clear();
  const root=createRoot(document.getElementById('root')!);
  await act(async()=>root.render(React.createElement(CustomerEntry,{config:{...config,customerAccessMode:'demo'},preview:true},React.createElement('div',{'data-testid':'library'},'Aulas'))));
  await act(async()=>click(button('Acessar conteúdo')));
  assert.match(document.body.textContent || '',/Não verifica compras/);
  const email=document.querySelector('input[type="email"]') as HTMLInputElement;
  await act(async()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value')!.set!.call(email,'test@example.com');email.dispatchEvent(new dom.window.Event('input',{bubbles:true}));});
  await act(async()=>click(button('Entrar na demonstração')));
  assert.ok(document.querySelector('[data-testid="library"]'));
  assert.equal(localStorage.length,0);
  await act(async()=>root.unmount());
});
test('first opening honors configured brand duration and animation, can be skipped, and does not repeat after entry',async(t)=>{
  localStorage.clear();
  let completeSplash:()=>void=()=>{};
  const timer=t.mock.method(window,'setTimeout',(callback:()=>void)=>{completeSplash=callback;return 123;});
  const cleared=t.mock.method(window,'clearTimeout',()=>{});
  const root=await render({...config,customSplash:true,splashDurationMs:3500,splashAnimation:'zoom'});
  assert.equal(timer.mock.calls[0].arguments[1],3500);
  assert.ok(document.querySelector('.customer-splash-zoom'));
  assert.equal(button('Acessar conteúdo'),undefined);
  await act(async()=>completeSplash());
  assert.ok(button('Acessar conteúdo'));
  await act(async()=>click(button('Acessar conteúdo')));
  await act(async()=>root.unmount());
  const returned=await render({...config,customSplash:true});
  assert.ok(document.querySelector('[data-testid="library"]'));
  assert.equal(document.querySelector('.customer-splash'),null);
  await act(async()=>returned.unmount());
  localStorage.clear();
  const skipped=await render({...config,customSplash:true,splashAnimation:'none'});
  await act(async()=>click(button('Continuar')));
  assert.ok(button('Acessar conteúdo'));
  assert.ok(cleared.mock.calls.some(call=>call.arguments[0]===123));
  await act(async()=>skipped.unmount());
  assert.equal(splashDuration({...config,splashDurationMs:NaN}),2500);
  assert.equal(splashDuration({...config,splashDurationMs:99999}),5000);
  assert.equal(splashDuration({...config,splashDurationMs:0}),1000);
});
test('disabling welcome opens content immediately and preserves completed entry for the next launch',async()=>{
  localStorage.clear();const root=await render({...config,welcomeEnabled:false,customerAccessMode:'demo'});
  assert.ok(document.querySelector('[data-testid="library"]'));
  assert.equal(document.querySelector('input'),null);
  assert.equal(localStorage.getItem(entryStorageKey(config.appName)),'done');
  await act(async()=>root.unmount());
  const returned=await render({...config,welcomeEnabled:false,customSplash:true});
  assert.ok(document.querySelector('[data-testid="library"]'));
  assert.equal(document.querySelector('.customer-splash'),null);
  await act(async()=>returned.unmount());
});
test('installation remains optional and Android instructions are available without a native prompt',async()=>{
  localStorage.clear();const root=await render();
  await act(async()=>click(button('Adicionar à tela inicial')));
  assert.match(document.body.textContent || '',/três pontos/);
  assert.equal(button('Instalar aplicativo'),undefined);
  await act(async()=>click(button('Continuar no navegador')));
  assert.ok(document.querySelector('[data-testid="library"]'));
  await act(async()=>root.unmount());
});
test('early captured prompt produces a real install button; browser acceptance is not reported as installed',async()=>{
  localStorage.clear();let prompts=0;
  const event=new dom.window.Event('beforeinstallprompt',{cancelable:true});
  Object.assign(event,{prompt:async()=>{prompts++;},userChoice:Promise.resolve({outcome:'accepted'})});dom.window.dispatchEvent(event);
  const root=await render({...config,customerAccessMode:'open'});
  await act(async()=>click(button('Adicionar à tela inicial')));
  assert.ok(button('Instalar aplicativo'));
  await act(async()=>click(button('Instalar aplicativo')));
  assert.equal(prompts,1);
  assert.match(document.body.textContent || '',/aceitou a instalação/);
  assert.equal(document.body.textContent?.includes('O aplicativo está instalado'),false);
  await act(async()=>dom.window.dispatchEvent(new dom.window.Event('appinstalled')));
  assert.match(document.body.textContent || '',/O aplicativo está instalado/);
  await act(async()=>click(button('Abrir meu conteúdo')));
  assert.ok(document.querySelector('[data-testid="library"]'));
  await act(async()=>root.unmount());
});
test('MP4 opening plays muted inline without looping, allows skipping, and advances when playback ends',async(t)=>{
  localStorage.clear();
  const play=t.mock.method(dom.window.HTMLMediaElement.prototype,'play',async()=>{});
  t.mock.method(dom.window.HTMLMediaElement.prototype,'pause',()=>{});
  const settings={...config,customSplash:true,splashMediaMode:'file' as const,splashMediaData:TEST_SPLASH_MP4,splashMediaFit:'cover' as const};
  const root=await render(settings);
  const video=document.querySelector('video')!;
  assert.equal(video.getAttribute('src'),TEST_SPLASH_MP4);
  assert.equal(video.muted,true);
  assert.equal(video.autoplay,true);
  assert.equal(video.playsInline,true);
  assert.equal(video.loop,false);
  assert.equal(video.controls,false);
  assert.equal(video.style.objectFit,'cover');
  assert.equal(play.mock.callCount(),1);
  await act(async()=>video.dispatchEvent(new dom.window.Event('ended')));
  assert.equal(document.querySelector('video'),null);
  assert.ok(button('Acessar conteúdo'));
  await act(async()=>root.unmount());
  const skipped=await render(settings);
  await act(async()=>click(button('Pular abertura')));
  assert.ok(button('Acessar conteúdo'));
  await act(async()=>skipped.unmount());
});
test('blocked autoplay and media errors restore the brand; stalled MP4 cannot trap the customer',async(t)=>{
  localStorage.clear();
  const play=t.mock.method(dom.window.HTMLMediaElement.prototype,'play',()=>Promise.reject(new Error('blocked')));
  t.mock.method(dom.window.HTMLMediaElement.prototype,'pause',()=>{});
  const settings={...config,customSplash:true,splashMediaMode:'file' as const,splashMediaData:TEST_SPLASH_MP4};
  const blocked=await render(settings);
  assert.equal(document.querySelector('video'),null);
  assert.ok(document.querySelector('.customer-brand'));
  await act(async()=>click(button('Continuar')));
  assert.ok(button('Acessar conteúdo'));
  await act(async()=>blocked.unmount());
  play.mock.mockImplementation(async()=>{});
  const broken=await render(settings);
  await act(async()=>document.querySelector('video')!.dispatchEvent(new dom.window.Event('error')));
  assert.equal(document.querySelector('video'),null);
  assert.ok(document.querySelector('.customer-brand'));
  await act(async()=>broken.unmount());
  let timeout:()=>void=()=>{};
  const timer=t.mock.method(window,'setTimeout',(callback:()=>void)=>{timeout=callback;return 123;});
  t.mock.method(window,'clearTimeout',()=>{});
  const stalled=await render(settings);
  assert.equal(timer.mock.calls[0].arguments[1],10000);
  await act(async()=>timeout());
  assert.equal(document.querySelector('video'),null);
  assert.ok(button('Acessar conteúdo'));
  await act(async()=>stalled.unmount());
});
test('animated image openings honor fit, background and configured duration, and invalid or disabled assets fall back safely',async(t)=>{
  localStorage.clear();let timeout:()=>void=()=>{};
  const timer=t.mock.method(window,'setTimeout',(callback:()=>void)=>{timeout=callback;return 123;});
  t.mock.method(window,'clearTimeout',()=>{});
  for (const source of [TEST_SPLASH_GIF,TEST_SPLASH_WEBP]) {
    const root=await render({...config,customSplash:true,splashDurationMs:3500,splashMediaMode:'file',splashMediaData:source,splashMediaBackground:'#123456'});
    assert.equal(document.querySelector('img')!.getAttribute('src'),source);
    assert.equal(document.querySelector('img')!.style.objectFit,'contain');
    assert.equal((document.querySelector('.customer-media-screen') as HTMLElement).style.background,'rgb(18, 52, 86)');
    assert.equal(timer.mock.calls.at(-1)!.arguments[1],3500);
    await act(async()=>timeout());
    assert.ok(button('Acessar conteúdo'));
    await act(async()=>root.unmount());
  }
  const invalid=await render({...config,customSplash:true,splashMediaMode:'file',splashMediaData:'data:text/html;base64,PHNjcmlwdD4='});
  assert.ok(document.querySelector('.customer-brand'));
  assert.equal(document.querySelector('video,iframe'),null);
  await act(async()=>invalid.unmount());
  const disabled=await render({...config,splashMediaMode:'file',splashMediaData:TEST_SPLASH_MP4});
  assert.equal(document.querySelector('video'),null);
  assert.ok(button('Acessar conteúdo'));
  await act(async()=>disabled.unmount());
});
test('entry and installation copy exists in every supported language and never references button color',async()=>{
  const { readFileSync }=await import('node:fs');
  const locales=['pt','en','es','fr'].map(lang=>JSON.parse(readFileSync(`src/locales/${lang}.json`,'utf8')));
  for(const locale of locales){
    assert.deepEqual(Object.keys(locale.experience).sort(),Object.keys(locales[0].experience).sort());
    assert.deepEqual(Object.keys(locale.experience.install).sort(),Object.keys(locales[0].experience.install).sort());
    assert.doesNotMatch(locale.onboarding.install.androidStep1,/azul|blue|bleu/i);
  }
  controller.dispose();
});
