import assert from 'node:assert/strict';
import test from 'node:test';
import { JSDOM } from 'jsdom';
import React, { act } from 'react';
import type { SubModule } from '../types';
import { TEST_MP3, TEST_M4A } from '../utils/fixtures/audioMp3';
const dom = new JSDOM('<div id="root"></div>', { url:'https://appify.test' });
Object.assign(globalThis, { window:dom.window, document:dom.window.document, DOMParser:dom.window.DOMParser, HTMLElement:dom.window.HTMLElement, localStorage:dom.window.localStorage, IS_REACT_ACT_ENVIRONMENT:true });
const { createRoot } = await import('react-dom/client');
const { ModulesAndContent } = await import('./ModulesAndContent');
const { useAppStore } = await import('../store/useAppStore');
const { getDefaultProps } = await import('../utils/builderHtml');
function click(element: Element) { element.dispatchEvent(new dom.window.MouseEvent('click',{bubbles:true})); }
function change(element: HTMLInputElement | HTMLSelectElement, value: string) {
  const proto = element.tagName === 'SELECT' ? dom.window.HTMLSelectElement.prototype : dom.window.HTMLInputElement.prototype;
  Object.getOwnPropertyDescriptor(proto,'value')!.set!.call(element,value);
  element.dispatchEvent(new dom.window.Event(element.tagName === 'SELECT' ? 'change' : 'input',{bubbles:true}));
}

test('M4A uploads generate a player and failed replacements display an error without discarding the current audio', async () => {
  const sub: SubModule = {id:7,name:'M4A',type:'html',htmlMode:'visual',contentType:'html',builder_data:[]};
  useAppStore.setState({editingSubmodule:{modId:1,subId:7},modules:[{id:1,name:'Módulo',iconName:'Book',status:'Ativo',subs:[sub]}]});
  const root = createRoot(document.getElementById('root')!);
  await act(async()=>root.render(React.createElement(ModulesAndContent,{submodule:sub,onSave:()=>{},onClose:()=>{}})));
  await act(async()=>click([...document.querySelectorAll('button')].find(b=>b.textContent?.includes('MP3, M4A ou link externo'))!));
  const upload = async (file: File) => {
    const loaded = new Promise<void>(resolve=>Object.assign(globalThis,{FileReader:class extends (dom.window.FileReader as typeof FileReader) { constructor(){super();this.addEventListener('loadend',()=>resolve());} }}));
    await act(async()=>{
      const input = document.querySelector('#audio-file')!;
      Object.defineProperty(input,'files',{configurable:true,value:[file]});
      input.dispatchEvent(new dom.window.Event('change',{bubbles:true})); await loaded;
    });
  };
  await upload(new dom.window.File([Buffer.from(TEST_M4A.split(',')[1],'base64')],'aula.m4a'));
  assert.equal(document.querySelector('audio')!.getAttribute('src'),TEST_M4A);
  assert.match(document.querySelector('[role="status"]')!.textContent!,/incorporado/);
  await upload(new dom.window.File(['<html>invalid</html>'],'invalid.m4a'));
  assert.match(document.querySelector('[role="alert"]')!.textContent!,/não corresponde/);
  assert.equal(document.querySelector('audio')!.getAttribute('src'),TEST_M4A);
  await act(async()=>click([...document.querySelectorAll('button')].find(b=>b.textContent?.includes('Salvar Aula'))!));
  assert.equal(new JSDOM(useAppStore.getState().modules[0].subs[0].contentHtml!).window.document.querySelector('audio')!.getAttribute('src'),TEST_M4A);
  await act(async()=>root.unmount());
  Object.assign(globalThis,{FileReader:dom.window.FileReader});
});

test('audio upload and URL modes save and reopen without losing the embedded MP3; removal clears the uploaded source', async (t) => {
  const errors = t.mock.method(console, 'error', () => {});
  const sub: SubModule = {id:6,name:'Áudio',type:'html',htmlMode:'visual',contentType:'html',builder_data:[]};
  useAppStore.setState({editingSubmodule:{modId:1,subId:6},modules:[{id:1,name:'Módulo',iconName:'Book',status:'Ativo',subs:[sub]}]});
  const root = createRoot(document.getElementById('root')!);
  const render = async (lesson: SubModule) => act(async()=>root.render(React.createElement(ModulesAndContent,{submodule:lesson,onSave:()=>{},onClose:()=>{}})));
  const save = async () => act(async()=>click([...document.querySelectorAll('button')].find(b=>b.textContent?.includes('Salvar Aula'))!));
  await render(sub);
  await act(async()=>click([...document.querySelectorAll('button')].find(b=>b.textContent?.includes('MP3, M4A ou link externo'))!));
  const loaded = new Promise<void>(resolve=>{
    Object.assign(globalThis,{FileReader:class extends (dom.window.FileReader as typeof FileReader) { constructor(){super();this.addEventListener('loadend',()=>resolve());} }});
  });
  await act(async()=>{
    const input = document.querySelector('#audio-file')!;
    Object.defineProperty(input,'files',{configurable:true,value:[new dom.window.File([Buffer.from(TEST_MP3.split(',')[1],'base64')],'aula.mp3')]});
    input.dispatchEvent(new dom.window.Event('change',{bubbles:true}));
    await loaded;
  });
  assert.equal(document.querySelector('audio')!.getAttribute('src'),TEST_MP3);
  await save();
  const saved = useAppStore.getState().modules[0].subs[0];
  assert.equal(saved.builder_data![0].props.audioFileName,'aula.mp3');
  await render(saved);
  await act(async()=>click(document.querySelector('.vpb-block-wrapper')!));
  assert.equal(document.querySelector('audio')!.getAttribute('src'),TEST_MP3);
  await act(async()=>change(document.querySelector('#audio-mode') as HTMLSelectElement,'url'));
  await act(async()=>change(document.querySelector('#audio-url') as HTMLInputElement,'https://example.com/aula.mp3'));
  assert.equal(document.querySelector('audio')!.getAttribute('src'),'https://example.com/aula.mp3');
  await save();
  const linked = useAppStore.getState().modules[0].subs[0];
  assert.equal(linked.builder_data![0].props.audioData,TEST_MP3);
  await render(linked);
  assert.equal(new JSDOM(linked.contentHtml!).window.document.querySelector('audio')!.getAttribute('src'),'https://example.com/aula.mp3');
  await act(async()=>change(document.querySelector('#audio-mode') as HTMLSelectElement,'file'));
  assert.equal(document.querySelector('audio')!.getAttribute('src'),TEST_MP3);
  await act(async()=>click([...document.querySelectorAll('button')].find(b=>b.textContent?.includes('Remover áudio'))!));
  await save();
  assert.equal(useAppStore.getState().modules[0].subs[0].builder_data![0].props.audioData,'');
  assert.equal(document.querySelector('audio'),null);
  await act(async()=>root.unmount());
  Object.assign(globalThis,{FileReader:dom.window.FileReader});
  assert.deepEqual(errors.mock.calls.map(call => call.arguments), [], 'Switching audio sources should not produce React input errors');
});

test('accordion toggles in the editor and persists edited content and initial state independently for duplicated sections', async () => {
  const sub: SubModule = {id:5,name:'Seções',type:'html',htmlMode:'visual',contentType:'html',builder_data:[]};
  useAppStore.setState({editingSubmodule:{modId:1,subId:5},modules:[{id:1,name:'Módulo',iconName:'Book',status:'Ativo',subs:[sub]}]});
  const root = createRoot(document.getElementById('root')!);
  const render = async (lesson: SubModule) => act(async()=>root.render(React.createElement(ModulesAndContent,{submodule:lesson,onSave:()=>{},onClose:()=>{}})));
  await render(sub);
  await act(async()=>click([...document.querySelectorAll('button')].find(b=>b.textContent?.includes('Acordeão'))!));
  assert.equal(document.querySelector('details')!.open,false);
  await act(async()=>click(document.querySelector('summary')!));
  assert.equal(document.querySelector('details')!.open,true);
  await act(async()=>click(document.querySelector('summary')!));
  assert.equal(document.querySelector('details')!.open,false);
  await act(async()=>change(document.querySelector('#accordion-title') as HTMLInputElement,'Cómo comenzar'));
  await act(async()=>{
    const textarea = document.querySelector('#accordion-content')!;
    Object.getOwnPropertyDescriptor(dom.window.HTMLTextAreaElement.prototype,'value')!.set!.call(textarea,'Primera línea\nSegunda línea');
    textarea.dispatchEvent(new dom.window.Event('input',{bubbles:true}));
  });
  await act(async()=>change(document.querySelector('#accordion-open') as HTMLSelectElement,'open'));
  await act(async()=>change(document.querySelector('[aria-label="Tamanho do título em pixels"]') as HTMLInputElement,'23'));
  await act(async()=>click(document.querySelector('[aria-label="Duplicar bloco"]')!));
  await act(async()=>change(document.querySelector('#accordion-title') as HTMLInputElement,'Otra sección'));
  await act(async()=>change(document.querySelector('#accordion-open') as HTMLSelectElement,'closed'));
  await act(async()=>click([...document.querySelectorAll('button')].find(b=>b.textContent?.includes('Salvar Aula'))!));
  const saved = useAppStore.getState().modules[0].subs[0];
  assert.equal(saved.builder_data![0].props.accordionOpen,true);
  assert.equal(saved.builder_data![1].props.accordionOpen,false);
  assert.equal(saved.builder_data![0].props.content,'Primera línea\nSegunda línea');
  await render(saved);
  const sections = document.querySelectorAll('details');
  assert.equal(sections.length,2);
  assert.equal(sections[0].open,true);
  assert.equal(sections[1].open,false);
  assert.equal(sections[0].querySelector('summary')!.textContent,'Cómo comenzar');
  assert.equal(sections[0].querySelector('summary')!.style.fontSize,'23px');
  const exported = new JSDOM(saved.contentHtml!).window.document.querySelectorAll('details');
  assert.equal(exported[0].open,true);
  assert.equal(exported[1].open,false);
  await act(async()=>click(sections[1].querySelector('summary')!));
  assert.equal(sections[1].open,true);
  assert.equal(sections[0].open,true);
  await act(async()=>root.unmount());
});

test('highlight card controls persist through saving and reopening and allow hiding the icon', async () => {
  const sub: SubModule = {id:4,name:'Destaque',type:'html',htmlMode:'visual',contentType:'html',builder_data:[]};
  useAppStore.setState({editingSubmodule:{modId:1,subId:4},modules:[{id:1,name:'Módulo',iconName:'Book',status:'Ativo',subs:[sub]}]});
  const root = createRoot(document.getElementById('root')!);
  const render = async (lesson: SubModule) => act(async()=>root.render(React.createElement(ModulesAndContent,{submodule:lesson,onSave:()=>{},onClose:()=>{}})));
  await render(sub);
  const save = async () => act(async()=>click([...document.querySelectorAll('button')].find(b=>b.textContent?.includes('Salvar Aula'))!));
  await act(async()=>click([...document.querySelectorAll('button')].find(b=>b.textContent?.includes('Card / Destaque'))!));
  assert.equal(document.querySelector('.appify-builder-card span'),null);
  await act(async()=>change(document.querySelector('#card-title') as HTMLInputElement,'Antes de comenzar'));
  await act(async()=>{
    const textarea = document.querySelector('#card-content')!;
    Object.getOwnPropertyDescriptor(dom.window.HTMLTextAreaElement.prototype,'value')!.set!.call(textarea,'Primera línea\nSegunda línea');
    textarea.dispatchEvent(new dom.window.Event('input',{bubbles:true}));
  });
  await act(async()=>change(document.querySelector('#card-icon') as HTMLSelectElement,'star'));
  await act(async()=>change(document.querySelector('[aria-label="Código da cor do fundo do card"]') as HTMLInputElement,'#123456'));
  await act(async()=>change(document.querySelector('#card-padding') as HTMLInputElement,'0'));
  await act(async()=>change(document.querySelector('#card-radius') as HTMLInputElement,'0'));
  await act(async()=>change(document.querySelector('[aria-label="Tamanho do título em pixels"]') as HTMLInputElement,'29'));
  await save();
  const saved = useAppStore.getState().modules[0].subs[0];
  assert.equal(saved.builder_data![0].type,'card');
  assert.equal(saved.builder_data![0].props.content,'Primera línea\nSegunda línea');
  await render(saved);
  await act(async()=>click(document.querySelector('.vpb-block-wrapper')!));
  assert.equal((document.querySelector('#card-icon') as HTMLSelectElement).value,'star');
  const preview = document.querySelector('.appify-builder-card') as HTMLElement;
  const exported = new JSDOM(saved.contentHtml!).window.document.querySelector('.appify-builder-card')!;
  assert.equal(preview.innerHTML,exported.innerHTML);
  assert.equal(preview.getAttribute('style'),exported.getAttribute('style'));
  assert.equal(preview.querySelector('h3')!.textContent,'Antes de comenzar');
  assert.equal(preview.querySelector('h3')!.style.fontSize,'29px');
  assert.equal(preview.style.padding,'0px');
  assert.equal(preview.style.borderRadius,'0px');
  await act(async()=>change(document.querySelector('#card-icon') as HTMLSelectElement,'none'));
  await save();
  assert.equal(new JSDOM(useAppStore.getState().modules[0].subs[0].contentHtml!).window.document.querySelector('.appify-builder-card span'),null);
  await act(async()=>root.unmount());
});

test('icon list can be added, edited, duplicated, saved and reopened in the visual editor', async () => {
  const sub: SubModule = {id:3,name:'Lista',type:'html',htmlMode:'visual',contentType:'html',builder_data:[]};
  useAppStore.setState({editingSubmodule:{modId:1,subId:3},modules:[{id:1,name:'Módulo',iconName:'Book',status:'Ativo',subs:[sub]}]});
  const root = createRoot(document.getElementById('root')!);
  const render = async (lesson: SubModule) => act(async()=>root.render(React.createElement(ModulesAndContent,{submodule:lesson,onSave:()=>{},onClose:()=>{}})));
  await render(sub);
  await act(async()=>click([...document.querySelectorAll('button')].find(b=>b.textContent?.includes('Lista com ícones'))!));
  assert.equal(document.querySelectorAll('.appify-builder-content li').length,3);
  await act(async()=>{
    const textarea = document.querySelector('#list-items')!;
    Object.getOwnPropertyDescriptor(dom.window.HTMLTextAreaElement.prototype,'value')!.set!.call(textarea,'Uno\nDos');
    textarea.dispatchEvent(new dom.window.Event('input',{bubbles:true}));
  });
  await act(async()=>change(document.querySelector('#list-icon') as HTMLSelectElement,'star'));
  await act(async()=>change(document.querySelector('[aria-label="Código da cor do ícone"]') as HTMLInputElement,'#123456'));
  await act(async()=>change(document.querySelector('#list-gap') as HTMLInputElement,'0'));
  assert.equal(document.querySelector('.appify-builder-content li')!.textContent,'★Uno');
  await act(async()=>click(document.querySelector('[aria-label="Duplicar bloco"]')!));
  await act(async()=>click([...document.querySelectorAll('button')].find(b=>b.textContent?.includes('Salvar Aula'))!));
  const saved = useAppStore.getState().modules[0].subs[0];
  assert.equal(saved.builder_data!.length,2);
  assert.notEqual(saved.builder_data![0].id,saved.builder_data![1].id);
  assert.equal(saved.builder_data![0].props.content,'Uno\nDos');
  assert.equal(saved.builder_data![0].props.listIcon,'star');
  assert.equal(saved.builder_data![0].props.listIconColor,'#123456');
  assert.equal(saved.builder_data![0].props.gap,'0');
  await render(saved);
  await act(async()=>click(document.querySelector('.vpb-block-wrapper')!));
  assert.equal((document.querySelector('#list-icon') as HTMLSelectElement).value,'star');
  assert.equal(document.querySelectorAll('.appify-builder-content li').length,4);
  assert.equal(new JSDOM(saved.contentHtml!).window.document.querySelectorAll('li').length,4);
  await act(async()=>root.unmount());
});

test('actual editor controls edit headings, duplicate, reorder, save and reopen without losing settings', async () => {
  const sub: SubModule = {id:1,name:'Aula',type:'html',htmlMode:'visual',contentType:'html',builder_data:[{id:'hero',type:'container',subtype:'hero',props:getDefaultProps('container','hero')},{id:'cards',type:'container',subtype:'threeColumn',props:getDefaultProps('container','threeColumn')}]};
  useAppStore.setState({editingSubmodule:{modId:1,subId:1},modules:[{id:1,name:'Módulo',iconName:'Book',status:'Ativo',subs:[sub]}]});
  let saved = false;
  const root = createRoot(document.getElementById('root')!);
  await act(async()=>{root.render(React.createElement(ModulesAndContent,{submodule:sub,onSave:()=>{saved=true;},onClose:()=>{}}));});
  await act(async()=>click(document.querySelector('.vpb-block-wrapper')!));
  await act(async()=>change(document.querySelector('[aria-label="Tamanho do título em pixels"]') as HTMLInputElement,'37'));
  const select = [...document.querySelectorAll('select')].find(select=>select.previousElementSibling?.textContent === 'Fonte do Título')!;
  await act(async()=>change(select,'Roboto'));
  const heading = document.querySelector('.appify-builder-content h1') as HTMLElement;
  assert.equal(heading.style.fontSize,'37px');
  assert.match(heading.style.fontFamily,/Roboto/);
  assert.equal((document.querySelector('[aria-label="Mover bloco para cima"]') as HTMLButtonElement).disabled,true);
  await act(async()=>click(document.querySelector('[aria-label="Duplicar bloco"]')!));
  assert.equal(document.querySelectorAll('.vpb-block-wrapper').length,3);
  await act(async()=>change(document.querySelector('[aria-label="Tamanho do título em pixels"]') as HTMLInputElement,'41'));
  assert.equal((document.querySelector('.appify-builder-content h1') as HTMLElement).style.fontSize,'37px');
  await act(async()=>click(document.querySelectorAll('[aria-label="Mover bloco para baixo"]')[1]));
  const save = [...document.querySelectorAll('button')].find(b=>b.textContent?.includes('Salvar Aula'))!;
  await act(async()=>click(save));
  assert.equal(saved,true);
  const lesson = useAppStore.getState().modules[0].subs[0];
  assert.equal(lesson.builder_data?.length,3);
  assert.equal(lesson.builder_data?.[2].props.titleFontSize,'41');
  assert.equal(lesson.builder_data?.[2].props.titleFontFamily,'Roboto');
  assert.match(lesson.contentHtml || '', /font-size:37px/);
  await act(async()=>root.unmount());
  const reopened = createRoot(document.getElementById('root')!);
  await act(async()=>reopened.render(React.createElement(ModulesAndContent,{submodule:lesson,onSave:()=>{},onClose:()=>{}})));
  assert.equal(document.querySelectorAll('.vpb-block-wrapper').length,3);
  assert.equal((document.querySelectorAll('.appify-builder-content h1')[1] as HTMLElement).style.fontSize,'41px');
  await act(async()=>reopened.unmount());
});

test('one-column controls survive saving; interactive opt-in is persisted per lesson and can be switched back to static',async()=>{
  const sub:SubModule={id:2,name:'Interação',type:'html',contentType:'html',htmlMode:'visual',builder_data:[]};
  useAppStore.setState({editingSubmodule:{modId:1,subId:2},modules:[{id:1,name:'Módulo',iconName:'Book',status:'Ativo',subs:[sub]}]});
  const root=createRoot(document.getElementById('root')!);
  const render=async(lesson:SubModule)=>act(async()=>root.render(React.createElement(ModulesAndContent,{submodule:lesson,onSave:()=>{},onClose:()=>{}})));
  await render(sub);
  const btn=(name:string)=>[...document.querySelectorAll('button')].find(node=>node.textContent?.includes(name))!;
  await act(async()=>click(btn('1 Coluna')));
  await act(async()=>change(document.querySelector('[aria-label="Largura máxima do conteúdo"]') as HTMLInputElement,'640'));
  await act(async()=>change(document.querySelector('[aria-label="Margem acima"]') as HTMLInputElement,'24'));
  await act(async()=>click(btn('Salvar Aula')));
  let saved=useAppStore.getState().modules[0].subs[0];
  assert.equal(saved.builder_data![0].subtype,'oneColumn');assert.equal(saved.builder_data![0].props.maxWidth,'640');
  assert.equal(saved.builder_data![0].props.marginTop,'24');
  await render(saved);
  await act(async()=>click(btn('Código HTML')));
  await act(async()=>change(document.querySelector('#html-execution-mode') as HTMLSelectElement,'interactive'));
  await act(async()=>click(btn('Salvar Aula')));
  saved=useAppStore.getState().modules[0].subs[0];assert.equal(saved.htmlInteractive,true);assert.equal(saved.htmlMode,'code');
  await render(saved);assert.equal((document.querySelector('#html-execution-mode') as HTMLSelectElement).value,'interactive');
  await act(async()=>change(document.querySelector('#html-execution-mode') as HTMLSelectElement,'static'));
  await act(async()=>click(btn('Salvar Aula')));assert.equal(useAppStore.getState().modules[0].subs[0].htmlInteractive,false);
  await act(async()=>root.unmount());
});
